apiVersion: v1
kind: Pod
metadata:
  name: pvc-hostpath-pod
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
    - name: claim-volume
      mountPath: /mnt
  volumes:
  - name: claim-volume
    persistentVolumeClaim:
      claimName: pvc-hostpath
  terminationGracePeriodSeconds: 0
