apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  annotations:
    gluster.org/type: file
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: glusterfile
